AnswerDotAI/gpu.cpp

examples/matmul/run.cpp
experimental/wgsl.h

WGSL of dawn/tint does not have the optimization of loop unrolling.
So this PR implements loop unrolling for matmul to check the performance of it.
In my environment(m2 pro), the result is as follows:
| Matmul version | GFLOPS|
|----------------|----------|
| 1D tiling without unrolling| 779.57 GFLOPS|
| 2D tiling without unrolling| 475.57 GFLOPS|
| 1D tiling with unrolling| 862.77 GFLOPS|
| 2D tiling with unrolling| 1288.09 GFLOPS|

Add loop unrolling for matmul

---

examples/matmul/run.cpp

This PR implements the vectorized matmul. 
FYI. There is no improvement or decrease in performance on m2 pro.

Add the vectorized matmul

---

Makefile
examples/README.md
examples/transpose/Makefile
examples/transpose/run.cpp

This implements transpose kernels in https://developer.nvidia.com/blog/efficient-matrix-transpose-cuda-cc/ .
The result of M2 pro is as follows:
|Version|GB/s|
|-------| ----|
|Naive Matrix Transpose (version = 1) | 74.85 GB/s| 
|Matrix Transpose with Shared Memory (version = 2) | 75.32 GB/s| 
|Matrix Transpose without GPU (version = 3) | 0.75 GB/s|

Add transpose kernels

---

README.md

Highlighting one cpp code block

Update README.md --style highlighting one cpp code block

---

examples/matmul/run.cpp

This PR implements matrix multiplication with transposed weight.
In case of NVIDIA, it will be 1.5 times faster.
```
$ yes |  MATMUL_VERSION=8  make  | grep 'Kernel version\|GFLOPS'
[info] Dispatching Kernel version 8: 2D blocktiling with loop unrolling and vectorization, 30 iterations ...
113.3 milliseconds / dispatch ~ 2426.99 GFLOPS
$ yes |  MATMUL_VERSION=9  make  | grep 'Kernel version\|GFLOPS'
[info] Dispatching Kernel version 9: 2D blocktiling with loop unrolling, vectorization and transpose, 30 iterations ...
74.7 milliseconds / dispatch ~ 3680.25 GFLOPS
$ yes |  MATMUL_VERSION=8  make  | grep 'Kernel version\|GFLOPS'
[info] Dispatching Kernel version 8: 2D blocktiling with loop unrolling and vectorization, 30 iterations ...
164.3 milliseconds / dispatch ~ 1672.82 GFLOPS
$ yes | …
```

Add matmul with transpose

---

examples/matmul/run.cpp

This PR changes https://github.com/AnswerDotAI/gpu.cpp/pull/35 to fix segfault.
The following points have been fixed:
1, Use getenv value immediately
2, Change the returned type of versionToStr to std::string, because lldb stoped at logger with versionToStr.

Fix: segfault of matmul with transpose

---

README.md

remove duplicate text

---

examples/matmul/run.cpp
gpu.h
utils/array_utils.h

This PR implements matrix multiplication with float16.
~~Mac's memory bandwidth is not enough for maximum floating point performance of the GPU. 
To improve performance, we need to reduce memory traffic.~~
https://github.com/AnswerDotAI/gpu.cpp/issues/40#issuecomment-2270142354
The result on M2 pro is as follows:
| Matmul version | GFLOPS|
|----------------|----------|
| 2D Matmul with float32(version = 8)| 1672.18 GFLOPS|
| Transposed 2D Matrix with float32(version = 9)| 1702.70 GFLOPS|
|  2D Matmul with float16(version = 10)| 3174.96 GFLOPS|
|  Transposed 2D Matmul with float16(version = 11)| 2889.82 GFLOPS|

Add matmul with float16

---

.gitignore
CMakeLists.txt
cmake/example.cmake
cmake/find_gpu.cmake
cmake/gpu.cmake
cmake/webgpu.cmake

This enables the project to be fetched with cmake FetchContent and to be directly built with cmake without calling the python script.
Solution to [this](https://github.com/AnswerDotAI/gpu.cpp/issues/42) issue

Using FetchContent to fetch libdawn.dylib from github when library not found

---

.gitignore
gpu.h

Found out this is available in the native headers but not the emscripten headers. This PR checks for and excludes the callback if emscripten. 
https://github.com/eliemichel/WebGPU-Cpp/blob/main/emscripten/webgpu.hpp
vs
https://github.com/eliemichel/WebGPU-Cpp/blob/main/dawn/webgpu.h

Fix emscripten deviceLostCallbackInfo

---

gpu.h
utils/logging.h

The way we were printing from LOG caused a crash when embedded on windows. This updates the logger to be more typesafe and generally compatible across platforms.
I removed exit(1) from the check function. We should never automatically exit the program as a library, this can prevent proper logging if there is indeed a crash.
Also introduces a NO_LOG definition that we should add throughout.
Also adds log level 0 for silent output.

Logger Fixes for Windows

---

utils/logging.h

LOG function calls `vsnprintf` with the same va_list twice, but it is not allowed.
It throws `segfault` sometimes.
This PR copies the va_list not to reuse it.
https://stackoverflow.com/questions/2288680/reuse-of-va-list

Fix va_list reuse

---

experimental/kernels/run.cpp

Fix the parameter of softmax-kernel. 
I added Cp of the extra parameter to softmax-kernel for llm.c.
But I did not update the parameter of run.cpp.

Fix softmax kernel with padding for llm.c

---

examples/matmul/Makefile
examples/matmul/run.cpp
experimental/kernels/Makefile
experimental/kernels/unittest_llmc/unittest_kernels.h
experimental/profiler/metal.hpp
experimental/profiler/metal.mm

This PR adds start/stopCapture functions to profile metal shader functions.
https://github.com/AnswerDotAI/gpu.cpp/issues/61
To call metal-functions on C++, we need to use objective-c++ or metal-cpp.
It simply provides C APIs using Objective-C.

Add metal_profiler to profile gpu on macos

---

Makefile
build.py

feat: 1. Modified the 'lib' rule in the Makefile file located in the root directory of the project, allowing it to generate gpu.cpp dynamic libraries with different suffixes based on the system.
2. By the build.py script, the header files in the gpu.hpp file are expanded in order to make gpu.hpp become true header-only source code.
3. 'install' and 'uninstall' rules are provided for scientific researchers who do not care about how to package applications, enabling them to quickly utilize gpu.cpp for gpu computation.

Some changes about the dynamic libraries generated by gpu.cpp project and header-only source code 'gpu.hpp'

---

README.md
README_cn.md

Change the 'gpu. h' in the English README.md document to 'gpu. hpp' and modify some translations in the Chinese README_cn.md document to make them more accurate.

Update and modify documents

---

experimental/kernels/Makefile
experimental/kernels/kernels.h
experimental/kernels/ops.cpp
experimental/kernels/unittest_llmc/unittest_kernels.cpp
gpu.hpp

This PR implements shader caching to reduce the cost of `createKernel`.
In case of matmul(https://github.com/AnswerDotAI/gpu.cpp/pull/67), the cost is about 50 times that of a GPU operation.
To do the caching, it changes the`Kernel` data-type to a shared pointer.

Implement kernel cache

---

experimental/kernels/Makefile
experimental/kernels/kernels.h
experimental/kernels/reduce.cpp
gpu.hpp

This PR implements reduction-kernels.
It works correctly, but it's only about twice as fast as CPU's one.
```
$ ./build/reduce
Initializing 67108864 values
[info] Requesting adapter
[info] Requesting device
[info] Waiting for device request to end
[info] Device request ended
Start testing sum(x) on 67108864 values
Duration(CPU): 4493.9 microseconds
sum_cpu: -3248.239746
Start testing sum(x) on 67108864 values
Duration(GPU): 2175.1 microseconds
sum_gpu: -3248.113770
Success: diff = 0.125977
Computed 67108864 values of kSum(x)
[info] Context destroyed
```

Add summation kernels

---

experimental/kernels/Makefile
experimental/kernels/gpt2_webgpu_aot.cpp
experimental/kernels/ops_aot.cpp
experimental/kernels/ops_aot.hpp

This PR implements the forward pass of gpt-2 with AoT.
The backward pass has been disabled as it needs to be fixed to not use atomicAdd.
There was a memory error and it was in draft state for a while.
I added `-fsanitize=address` to make it possible to detect errors.
The memory error has been fixed.

Add the ops of AoT

---

bindings/haskell/gpu-cpp.cabal
bindings/python/Makefile
bindings/python/gpu_cpp.cpp

Fix python bindings to use the shared pointer of RawKernel.

Fix pybind
